### ISSUE TITLE
Ubuntu 22.10, deb package: missing libssl.so.1.1

### ISSUE THREAD

**Issue by hydrandt** [pacholoamit/pachtop#5]
On Ubuntu 22.10, after installing pachtop_0.3.1_amd64.deb, the application can't be started, complaining about a missing library:

`pachtop: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`

The AppImage version works.

Ubuntu 22.10 comes with libssl3, (openssl v3), and it doesn't seem to me 1.1 would be available. Possible to build against it?

**Comment by pacholoamit** [comment]
Hello, That's unfortunate. Pachtop is still in development and isn't stable. I used [Tauri](https://tauri.app/)  to package the application and cross-compile them into binaries. Perhaps I should adjust the version targets when compiling the binaries?

I found a post that shares a similar: https://stackoverflow.com/questions/72133316/libssl-so-1-1-cannot-open-shared-object-file-no-such-file-or-directory

I'm glad the app image works though.
